#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_BGA_FireworksMortar_Holder

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK::Params
{

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.ExecuteUbergraph_B_BGA_FireworksMortar_Holder
// 0x05E0 (0x05E0 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class AActor* DamagedActor, float Damage, class AController* InstigatedBy, class AActor* DamageCauser, const struct FVector& HitLocation, class UPrimitiveComponent* FHitComponent, class FName BoneName, const struct FVector& Momentum)> K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class AActor* DestroyedActor)> K2Node_CreateDelegate_OutputDelegate1;             // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class AActor* DamagedActor, float Damage, class AController* InstigatedBy, class AActor* DamageCauser, const struct FVector& HitLocation, class UPrimitiveComponent* FHitComponent, class FName BoneName, const struct FVector& Momentum)> K2Node_CreateDelegate_OutputDelegate2;             // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class AActor* DestroyedActor)> K2Node_CreateDelegate_OutputDelegate3;             // 0x0034(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0048(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	struct FRotator                               K2Node_CustomEvent_PlayerYaw;                      // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         K2Node_CustomEvent_YawOffset;                      // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array1;                           // 0x0078(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0088(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0094(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData;               // 0x00A0(0x00A8)()
	TArray<class AActor*>                         CallFunc_SphereOverlapActors_OutActors;            // 0x0148(0x0010)(ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_SphereOverlapActors_ReturnValue;          // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_MultiGate_FirstRun;                         // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15A[0x2];                                      // 0x015A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_MultiGate_Data;                             // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_MultiGate_ScratchBool;                      // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_161[0x3];                                      // 0x0161(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_MultiGate_ScratchIndex;                     // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_DestroyedActor;                 // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0174(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_MakeStruct_GameplayCueParameters;           // 0x0180(0x00B8)(ContainsInstancedReference)
	class AActor*                                 K2Node_CustomEvent_DamagedActor;                   // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_Damage;                         // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            K2Node_CustomEvent_InstigatedBy;                   // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_DamageCauser;                   // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_HitLocation;                    // 0x0258(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_264[0x4];                                      // 0x0264(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_CustomEvent_FHitComponent;                  // 0x0268(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_BoneName;                       // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Momentum;                       // 0x0278(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0284(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_285[0x3];                                      // 0x0285(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x028C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue1;         // 0x0290(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29C[0x4];                                      // 0x029C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_CustomEvent_AttachActor;                    // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_CustomEvent_Hit;                            // 0x02A8(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	int32                                         Temp_int_Variable;                                 // 0x0330(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0334(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0335(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_336[0x2];                                      // 0x0336(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x033C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0340(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x034C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0358(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0364(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0380(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0390(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0394(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0398(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x03A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortAthenaVehicle*                     K2Node_DynamicCast_AsFort_Athena_Vehicle;          // 0x03B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x03B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B9[0x7];                                      // 0x03B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABuildingActor*                         K2Node_DynamicCast_AsBuilding_Actor;               // 0x03C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess1;                      // 0x03C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x03C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3CA[0x6];                                      // 0x03CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_Event_MyComp;                               // 0x03D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Other;                                // 0x03D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_Event_OtherComp;                            // 0x03E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bSelfMoved;                           // 0x03E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E9[0x3];                                      // 0x03E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                K2Node_Event_HitLocation;                          // 0x03EC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_HitNormal;                            // 0x03F8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_NormalImpulse;                        // 0x0404(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_Hit;                                  // 0x0410(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x0498(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49C[0x4];                                      // 0x049C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_DynamicCast_AsPawn;                         // 0x04A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x04A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A9[0x3];                                      // 0x04A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_DegAcos_ReturnValue;                      // 0x04AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x04B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B1[0x7];                                      // 0x04B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_CustomEvent_Actor;                          // 0x04B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABuildingActor*                         K2Node_DynamicCast_AsBuilding_Actor1;              // 0x04C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess3;                      // 0x04C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4C9[0x3];                                      // 0x04C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Array_Get_Item;                           // 0x04CC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue1;                  // 0x04D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x04D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4D9[0x3];                                      // 0x04D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x04DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x04E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4E1[0x7];                                      // 0x04E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item1;                          // 0x04E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABuildingActor*                         K2Node_DynamicCast_AsBuilding_Actor2;              // 0x04F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess4;                      // 0x04F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4F9[0x3];                                      // 0x04F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x04FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item2;                          // 0x0500(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EGameplayCueEvent                             K2Node_GameplayCueEvent_EventType;                 // 0x0508(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_509[0x7];                                      // 0x0509(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 K2Node_GameplayCueEvent_Parameters;                // 0x0510(0x00B8)(ContainsInstancedReference)
	TArray<EFortTeamAffiliation>                  K2Node_MakeArray_Array2;                           // 0x05C8(0x0010)(ZeroConstructor, ReferenceParm)
	uint8                                         CallFunc_GetActorTeam_ReturnValue;                 // 0x05D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder) == 0x000008, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder) == 0x0005E0, "Wrong size on B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, EntryPoint) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CreateDelegate_OutputDelegate1) == 0x000014, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CreateDelegate_OutputDelegate1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CreateDelegate_OutputDelegate2) == 0x000024, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CreateDelegate_OutputDelegate2' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CreateDelegate_OutputDelegate3) == 0x000034, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CreateDelegate_OutputDelegate3' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MakeArray_Array) == 0x000048, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_PlayerYaw) == 0x000058, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_PlayerYaw' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_YawOffset) == 0x000064, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_YawOffset' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakRotator_Roll) == 0x000068, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakRotator_Pitch) == 0x00006C, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakRotator_Yaw) == 0x000070, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MakeArray_Array1) == 0x000078, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MakeArray_Array1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_MakeRotator_ReturnValue) == 0x000088, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000094, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MakeStruct_GameplayEventData) == 0x0000A0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MakeStruct_GameplayEventData' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_SphereOverlapActors_OutActors) == 0x000148, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_SphereOverlapActors_OutActors' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_SphereOverlapActors_ReturnValue) == 0x000158, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_SphereOverlapActors_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MultiGate_FirstRun) == 0x000159, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MultiGate_FirstRun' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MultiGate_Data) == 0x00015C, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MultiGate_Data' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MultiGate_ScratchBool) == 0x000160, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MultiGate_ScratchBool' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MultiGate_ScratchIndex) == 0x000164, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MultiGate_ScratchIndex' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_DestroyedActor) == 0x000168, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_DestroyedActor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_HasAuthority_ReturnValue) == 0x000170, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000174, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MakeStruct_GameplayCueParameters) == 0x000180, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MakeStruct_GameplayCueParameters' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_DamagedActor) == 0x000238, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_DamagedActor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_Damage) == 0x000240, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_Damage' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_InstigatedBy) == 0x000248, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_InstigatedBy' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_DamageCauser) == 0x000250, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_DamageCauser' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_HitLocation) == 0x000258, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_HitLocation' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_FHitComponent) == 0x000268, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_FHitComponent' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_BoneName) == 0x000270, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_BoneName' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_Momentum) == 0x000278, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_Momentum' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_IsServer_ReturnValue) == 0x000284, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, Temp_int_Loop_Counter_Variable) == 0x000288, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Add_IntInt_ReturnValue) == 0x00028C, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_K2_GetActorLocation_ReturnValue1) == 0x000290, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_K2_GetActorLocation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_AttachActor) == 0x0002A0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_AttachActor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_Hit) == 0x0002A8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_Hit' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, Temp_int_Variable) == 0x000330, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_bBlockingHit) == 0x000334, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_bInitialOverlap) == 0x000335, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_Time) == 0x000338, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_Distance) == 0x00033C, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_Location) == 0x000340, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_ImpactPoint) == 0x00034C, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_Normal) == 0x000358, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_ImpactNormal) == 0x000364, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_PhysMat) == 0x000370, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_HitActor) == 0x000378, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_HitComponent) == 0x000380, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_HitBoneName) == 0x000388, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_HitItem) == 0x000390, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_FaceIndex) == 0x000394, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_TraceStart) == 0x000398, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_BreakHitResult_TraceEnd) == 0x0003A4, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_AsFort_Athena_Vehicle) == 0x0003B0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_AsFort_Athena_Vehicle' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_bSuccess) == 0x0003B8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_AsBuilding_Actor) == 0x0003C0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_AsBuilding_Actor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_bSuccess1) == 0x0003C8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_bSuccess1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_IsValid_ReturnValue) == 0x0003C9, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_MyComp) == 0x0003D0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_MyComp' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_Other) == 0x0003D8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_Other' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_OtherComp) == 0x0003E0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_OtherComp' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_bSelfMoved) == 0x0003E8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_bSelfMoved' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_HitLocation) == 0x0003EC, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_HitLocation' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_HitNormal) == 0x0003F8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_HitNormal' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_NormalImpulse) == 0x000404, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_NormalImpulse' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_Event_Hit) == 0x000410, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_Event_Hit' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Dot_VectorVector_ReturnValue) == 0x000498, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_AsPawn) == 0x0004A0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_AsPawn' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_bSuccess2) == 0x0004A8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_DegAcos_ReturnValue) == 0x0004AC, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_DegAcos_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Less_FloatFloat_ReturnValue) == 0x0004B0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_CustomEvent_Actor) == 0x0004B8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_CustomEvent_Actor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_AsBuilding_Actor1) == 0x0004C0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_AsBuilding_Actor1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_bSuccess3) == 0x0004C8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_bSuccess3' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Array_Get_Item) == 0x0004CC, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Add_IntInt_ReturnValue1) == 0x0004D4, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Add_IntInt_ReturnValue1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0004D8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Array_Length_ReturnValue) == 0x0004DC, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Less_IntInt_ReturnValue) == 0x0004E0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Array_Get_Item1) == 0x0004E8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Array_Get_Item1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_AsBuilding_Actor2) == 0x0004F0, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_AsBuilding_Actor2' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_DynamicCast_bSuccess4) == 0x0004F8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_DynamicCast_bSuccess4' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, Temp_int_Array_Index_Variable) == 0x0004FC, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_Array_Get_Item2) == 0x000500, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_GameplayCueEvent_EventType) == 0x000508, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_GameplayCueEvent_EventType' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_GameplayCueEvent_Parameters) == 0x000510, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_GameplayCueEvent_Parameters' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, K2Node_MakeArray_Array2) == 0x0005C8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::K2Node_MakeArray_Array2' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder, CallFunc_GetActorTeam_ReturnValue) == 0x0005D8, "Member 'B_BGA_FireworksMortar_Holder_C_ExecuteUbergraph_B_BGA_FireworksMortar_Holder::CallFunc_GetActorTeam_ReturnValue' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.GameplayCue.Athena.FireworksMortar.MuzzleFlash
// 0x00C0 (0x00C0 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash final
{
public:
	EGameplayCueEvent                             EventType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash) == 0x000008, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash) == 0x0000C0, "Wrong size on B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash, EventType) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash::EventType' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash, Parameters) == 0x000008, "Member 'B_BGA_FireworksMortar_Holder_C_GameplayCue_Athena_FireworksMortar_MuzzleFlash::Parameters' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.HandleBinding
// 0x0008 (0x0008 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_HandleBinding final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_HandleBinding) == 0x000008, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_HandleBinding");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_HandleBinding) == 0x000008, "Wrong size on B_BGA_FireworksMortar_Holder_C_HandleBinding");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_HandleBinding, Actor) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_HandleBinding::Actor' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.AttachMortar
// 0x0090 (0x0090 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_AttachMortar final
{
public:
	class AActor*                                 AttachActor;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0008(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_AttachMortar) == 0x000008, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_AttachMortar");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_AttachMortar) == 0x000090, "Wrong size on B_BGA_FireworksMortar_Holder_C_AttachMortar");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_AttachMortar, AttachActor) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_AttachMortar::AttachActor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_AttachMortar, Hit) == 0x000008, "Member 'B_BGA_FireworksMortar_Holder_C_AttachMortar::Hit' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.SetRotation
// 0x0010 (0x0010 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_SetRotation final
{
public:
	struct FRotator                               PlayerYaw;                                         // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         YawOffset_0;                                       // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_SetRotation) == 0x000004, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_SetRotation");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_SetRotation) == 0x000010, "Wrong size on B_BGA_FireworksMortar_Holder_C_SetRotation");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_SetRotation, PlayerYaw) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_SetRotation::PlayerYaw' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_SetRotation, YawOffset_0) == 0x00000C, "Member 'B_BGA_FireworksMortar_Holder_C_SetRotation::YawOffset_0' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.BaseDestroyed
// 0x0008 (0x0008 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_BaseDestroyed final
{
public:
	class AActor*                                 DestroyedActor;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_BaseDestroyed) == 0x000008, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_BaseDestroyed");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_BaseDestroyed) == 0x000008, "Wrong size on B_BGA_FireworksMortar_Holder_C_BaseDestroyed");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDestroyed, DestroyedActor) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDestroyed::DestroyedActor' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.BaseDied
// 0x0050 (0x0050 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_BaseDied final
{
public:
	class AActor*                                 DamagedActor;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            InstigatedBy;                                      // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                HitLocation;                                       // 0x0020(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    FHitComponent;                                     // 0x0030(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   BoneName;                                          // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Momentum;                                          // 0x0040(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_BaseDied) == 0x000008, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_BaseDied");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_BaseDied) == 0x000050, "Wrong size on B_BGA_FireworksMortar_Holder_C_BaseDied");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, DamagedActor) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::DamagedActor' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, Damage) == 0x000008, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::Damage' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, InstigatedBy) == 0x000010, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::InstigatedBy' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, DamageCauser) == 0x000018, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::DamageCauser' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, HitLocation) == 0x000020, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::HitLocation' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, FHitComponent) == 0x000030, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::FHitComponent' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, BoneName) == 0x000038, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::BoneName' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_BaseDied, Momentum) == 0x000040, "Member 'B_BGA_FireworksMortar_Holder_C_BaseDied::Momentum' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.ReceiveHit
// 0x00C8 (0x00C8 - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_ReceiveHit final
{
public:
	class UPrimitiveComponent*                    MyComp;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Other;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bSelfMoved;                                        // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                HitLocation;                                       // 0x001C(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                HitNormal_0;                                       // 0x0028(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0034(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0040(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_ReceiveHit) == 0x000008, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_ReceiveHit");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_ReceiveHit) == 0x0000C8, "Wrong size on B_BGA_FireworksMortar_Holder_C_ReceiveHit");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, MyComp) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::MyComp' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, Other) == 0x000008, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::Other' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, OtherComp) == 0x000010, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::OtherComp' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, bSelfMoved) == 0x000018, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::bSelfMoved' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, HitLocation) == 0x00001C, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::HitLocation' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, HitNormal_0) == 0x000028, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::HitNormal_0' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, NormalImpulse) == 0x000034, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::NormalImpulse' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_ReceiveHit, Hit) == 0x000040, "Member 'B_BGA_FireworksMortar_Holder_C_ReceiveHit::Hit' has a wrong offset!");

// Function B_BGA_FireworksMortar_Holder.B_BGA_FireworksMortar_Holder_C.OnRep_ApplyRotation
// 0x016C (0x016C - 0x0000)
struct B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation final
{
public:
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotFromZX_ReturnValue;                // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult;    // 0x0030(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue1;                 // 0x00B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult1;   // 0x00C4(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_BreakRotator_Roll1;                       // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch1;                      // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw1;                        // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue2;                 // 0x015C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_SetActorRotation_ReturnValue;          // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation) == 0x000004, "Wrong alignment on B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation");
static_assert(sizeof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation) == 0x00016C, "Wrong size on B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_GetForwardVector_ReturnValue) == 0x000000, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_MakeRotFromZX_ReturnValue) == 0x00000C, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_MakeRotFromZX_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_MakeRotator_ReturnValue) == 0x000018, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_BreakRotator_Roll) == 0x000024, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_BreakRotator_Pitch) == 0x000028, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_BreakRotator_Yaw) == 0x00002C, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_K2_SetRelativeRotation_SweepHitResult) == 0x000030, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_K2_SetRelativeRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_MakeRotator_ReturnValue1) == 0x0000B8, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_MakeRotator_ReturnValue1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_K2_SetRelativeRotation_SweepHitResult1) == 0x0000C4, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_K2_SetRelativeRotation_SweepHitResult1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_BreakRotator_Roll1) == 0x00014C, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_BreakRotator_Roll1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_BreakRotator_Pitch1) == 0x000150, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_BreakRotator_Pitch1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_BreakRotator_Yaw1) == 0x000154, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_BreakRotator_Yaw1' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_Add_FloatFloat_ReturnValue) == 0x000158, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_MakeRotator_ReturnValue2) == 0x00015C, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_MakeRotator_ReturnValue2' has a wrong offset!");
static_assert(offsetof(B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation, CallFunc_K2_SetActorRotation_ReturnValue) == 0x000168, "Member 'B_BGA_FireworksMortar_Holder_C_OnRep_ApplyRotation::CallFunc_K2_SetActorRotation_ReturnValue' has a wrong offset!");

}

