#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_Balloons_Consumable_Rope

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BGA_Balloons_Consumable_Rope.BGA_Balloons_Consumable_Rope_C
// 0x0010 (0x0778 - 0x0768)
class ABGA_Balloons_Consumable_Rope_C final : public ABuildingGameplayActorBalloonRope
{
public:
	class USkeletalMeshComponentBudgeted*         Balloon_SKBudgeted;                                // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       Sphere;                                            // 0x0770(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BGA_Balloons_Consumable_Rope_C">();
	}
	static class ABGA_Balloons_Consumable_Rope_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABGA_Balloons_Consumable_Rope_C>();
	}
};
static_assert(alignof(ABGA_Balloons_Consumable_Rope_C) == 0x000008, "Wrong alignment on ABGA_Balloons_Consumable_Rope_C");
static_assert(sizeof(ABGA_Balloons_Consumable_Rope_C) == 0x000778, "Wrong size on ABGA_Balloons_Consumable_Rope_C");
static_assert(offsetof(ABGA_Balloons_Consumable_Rope_C, Balloon_SKBudgeted) == 0x000768, "Member 'ABGA_Balloons_Consumable_Rope_C::Balloon_SKBudgeted' has a wrong offset!");
static_assert(offsetof(ABGA_Balloons_Consumable_Rope_C, Sphere) == 0x000770, "Member 'ABGA_Balloons_Consumable_Rope_C::Sphere' has a wrong offset!");

}

