#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_Instance_PlaysetGrenadeWithTrajectory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Athena_PlaysetGrenadeWithTrajectory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_Instance_PlaysetGrenadeWithTrajectory.GA_Athena_Instance_PlaysetGrenadeWithTrajectory_C
// 0x0010 (0x0C70 - 0x0C60)
class UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C : public UGA_Athena_PlaysetGrenadeWithTrajectory_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Athena_Instance_PlaysetGrenadeWithTrajectory_C; // 0x0C60(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFortPlaysetItemDefinition*             PlaysetData;                                       // 0x0C68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Athena_Instance_PlaysetGrenadeWithTrajectory(int32 EntryPoint);
	void GetActivePlaysetData(class UFortPlaysetItemDefinition** OutData);
	void SetActivePlaysetOnPlayer();
	void SetPlaysetData(class AFortProjectileBase* Projectile_Reference);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_Instance_PlaysetGrenadeWithTrajectory_C">();
	}
	static class UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C>();
	}
};
static_assert(alignof(UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C) == 0x000008, "Wrong alignment on UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C");
static_assert(sizeof(UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C) == 0x000C70, "Wrong size on UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C");
static_assert(offsetof(UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C, UberGraphFrame_GA_Athena_Instance_PlaysetGrenadeWithTrajectory_C) == 0x000C60, "Member 'UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C::UberGraphFrame_GA_Athena_Instance_PlaysetGrenadeWithTrajectory_C' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C, PlaysetData) == 0x000C68, "Member 'UGA_Athena_Instance_PlaysetGrenadeWithTrajectory_C::PlaysetData' has a wrong offset!");

}

