#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GAB_Melee_Generic_EventGraph

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.ExecuteUbergraph_GAB_Melee_Generic_EventGraph
// 0x01A0 (0x01A0 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData2;                    // 0x0008(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag2;                // 0x0028(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData;                     // 0x0030(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag;                 // 0x0050(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate;              // 0x0058(0x0010)(ZeroConstructor, NoDestructor)
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x0068(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       Temp_struct_Variable1;                             // 0x0070(0x0020)()
	int32                                         Temp_int_Variable;                                 // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityActorInfo              CallFunc_GetActorInfo_ReturnValue;                 // 0x0098(0x0040)(ContainsInstancedReference)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_TargetData1;                    // 0x00D8(0x0020)(ConstParm)
	struct FGameplayTag                           K2Node_CustomEvent_ApplicationTag1;                // 0x00F8(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_AbilityTargetDataFromActor_ReturnValue;   // 0x0110(0x0020)()
	TArray<struct FActiveGameplayEffectHandle>    CallFunc_BP_ApplyGameplayEffectToTarget_ReturnValue; // 0x0130(0x0010)(ZeroConstructor, ReferenceParm)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate1;             // 0x0140(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag)> K2Node_CreateDelegate_OutputDelegate2;             // 0x0150(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_162[0x6];                                      // 0x0162(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortAbilityTask_PlayMontageWaitTarget* CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue; // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_CommitAbility_ReturnValue;             // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_CommitAbility_ReturnValue1;            // 0x0172(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_173[0x1];                                      // 0x0173(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetCurrentAbilitySourceLevel_OutSourceLevel; // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FActiveGameplayEffectHandle>    CallFunc_ApplyGameplayEffectContainer_ReturnValue; // 0x0180(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x3];                                      // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph) == 0x0001A0, "Wrong size on GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, EntryPoint) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::EntryPoint' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CustomEvent_TargetData2) == 0x000008, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CustomEvent_TargetData2' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CustomEvent_ApplicationTag2) == 0x000028, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CustomEvent_ApplicationTag2' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CustomEvent_TargetData) == 0x000030, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CustomEvent_TargetData' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CustomEvent_ApplicationTag) == 0x000050, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CustomEvent_ApplicationTag' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CreateDelegate_OutputDelegate) == 0x000058, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, Temp_struct_Variable) == 0x000068, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, Temp_struct_Variable1) == 0x000070, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::Temp_struct_Variable1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, Temp_int_Variable) == 0x000090, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_GetActorInfo_ReturnValue) == 0x000098, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_GetActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CustomEvent_TargetData1) == 0x0000D8, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CustomEvent_TargetData1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CustomEvent_ApplicationTag1) == 0x0000F8, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CustomEvent_ApplicationTag1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x000100, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_DynamicCast_bSuccess) == 0x000108, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_AbilityTargetDataFromActor_ReturnValue) == 0x000110, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_AbilityTargetDataFromActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_BP_ApplyGameplayEffectToTarget_ReturnValue) == 0x000130, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_BP_ApplyGameplayEffectToTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CreateDelegate_OutputDelegate1) == 0x000140, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CreateDelegate_OutputDelegate1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, K2Node_CreateDelegate_OutputDelegate2) == 0x000150, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::K2Node_CreateDelegate_OutputDelegate2' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, Temp_bool_IsClosed_Variable) == 0x000160, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, Temp_bool_Has_Been_Initd_Variable) == 0x000161, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue) == 0x000168, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_PlayMontageInfoAndWaitForTrigger_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_IsValid_ReturnValue) == 0x000170, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_K2_CommitAbility_ReturnValue) == 0x000171, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_K2_CommitAbility_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_K2_CommitAbility_ReturnValue1) == 0x000172, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_K2_CommitAbility_ReturnValue1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_GetCurrentAbilitySourceLevel_OutSourceLevel) == 0x000174, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_GetCurrentAbilitySourceLevel_OutSourceLevel' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_FTrunc_ReturnValue) == 0x000178, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_ApplyGameplayEffectContainer_ReturnValue) == 0x000180, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_ApplyGameplayEffectContainer_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_Greater_IntInt_ReturnValue) == 0x000190, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_Add_IntInt_ReturnValue) == 0x000194, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000198, "Member 'GAB_Melee_Generic_EventGraph_C_ExecuteUbergraph_GAB_Melee_Generic_EventGraph::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.Triggered_8C20D6D3411A3D7E54D6049F69DF10BE
// 0x0028 (0x0028 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE) == 0x000028, "Wrong size on GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE, TargetData) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE, ApplicationTag) == 0x000020, "Member 'GAB_Melee_Generic_EventGraph_C_Triggered_8C20D6D3411A3D7E54D6049F69DF10BE::ApplicationTag' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE
// 0x0028 (0x0028 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE) == 0x000028, "Wrong size on GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE, TargetData) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE, ApplicationTag) == 0x000020, "Member 'GAB_Melee_Generic_EventGraph_C_Cancelled_8C20D6D3411A3D7E54D6049F69DF10BE::ApplicationTag' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.Completed_8C20D6D3411A3D7E54D6049F69DF10BE
// 0x0028 (0x0028 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE final
{
public:
	struct FGameplayAbilityTargetDataHandle       TargetData;                                        // 0x0000(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FGameplayTag                           ApplicationTag;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE) == 0x000028, "Wrong size on GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE, TargetData) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE::TargetData' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE, ApplicationTag) == 0x000020, "Member 'GAB_Melee_Generic_EventGraph_C_Completed_8C20D6D3411A3D7E54D6049F69DF10BE::ApplicationTag' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.SetKnockbackImmunity
// 0x0020 (0x0020 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity final
{
public:
	bool                                          ImmunityOn;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEffectSpecHandle              CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue; // 0x0008(0x0010)()
	struct FActiveGameplayEffectHandle            CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue; // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity) == 0x000020, "Wrong size on GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity, ImmunityOn) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity::ImmunityOn' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity, CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue) == 0x000008, "Member 'GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity::CallFunc_MakeOutgoingGameplayEffectSpec_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity, CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue) == 0x000018, "Member 'GAB_Melee_Generic_EventGraph_C_SetKnockbackImmunity::CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.SetPawnCollision
// 0x0018 (0x0018 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_SetPawnCollision final
{
public:
	class AFortPawn*                              FortPawn;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CollisionOn;                                       // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_NameName_ReturnValue;            // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B[0x1];                                        // 0x000B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_GetCollisionProfileName_ReturnValue;      // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_SetPawnCollision) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_SetPawnCollision");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_SetPawnCollision) == 0x000018, "Wrong size on GAB_Melee_Generic_EventGraph_C_SetPawnCollision");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetPawnCollision, FortPawn) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_SetPawnCollision::FortPawn' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetPawnCollision, CollisionOn) == 0x000008, "Member 'GAB_Melee_Generic_EventGraph_C_SetPawnCollision::CollisionOn' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetPawnCollision, CallFunc_NotEqual_NameName_ReturnValue) == 0x000009, "Member 'GAB_Melee_Generic_EventGraph_C_SetPawnCollision::CallFunc_NotEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetPawnCollision, CallFunc_IsValid_ReturnValue) == 0x00000A, "Member 'GAB_Melee_Generic_EventGraph_C_SetPawnCollision::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_SetPawnCollision, CallFunc_GetCollisionProfileName_ReturnValue) == 0x00000C, "Member 'GAB_Melee_Generic_EventGraph_C_SetPawnCollision::CallFunc_GetCollisionProfileName_ReturnValue' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.Get_X_Y_Distance_Between_Vectors
// 0x0044 (0x0044 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors final
{
public:
	struct FVector                                Vector1;                                           // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Vector2;                                           // 0x000C(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         X_Y_Distance;                                      // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x001C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Square_ReturnValue;                       // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Square_ReturnValue1;                      // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Sqrt_ReturnValue;                         // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors) == 0x000004, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors) == 0x000044, "Wrong size on GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, Vector1) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::Vector1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, Vector2) == 0x00000C, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::Vector2' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, X_Y_Distance) == 0x000018, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::X_Y_Distance' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_Subtract_VectorVector_ReturnValue) == 0x00001C, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_BreakVector_X) == 0x000028, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_BreakVector_Y) == 0x00002C, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_BreakVector_Z) == 0x000030, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_Square_ReturnValue) == 0x000034, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_Square_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_Square_ReturnValue1) == 0x000038, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_Square_ReturnValue1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_Add_FloatFloat_ReturnValue) == 0x00003C, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors, CallFunc_Sqrt_ReturnValue) == 0x000040, "Member 'GAB_Melee_Generic_EventGraph_C_Get_X_Y_Distance_Between_Vectors::CallFunc_Sqrt_ReturnValue' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.GetLocationAtDistanceFromActorFacing
// 0x0048 (0x0048 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Distance;                                          // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Location;                                          // 0x000C(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x0024(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x003C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing) == 0x000048, "Wrong size on GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing, Actor) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing::Actor' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing, Distance) == 0x000008, "Member 'GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing::Distance' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing, Location) == 0x00000C, "Member 'GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing::Location' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000018, "Member 'GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing, CallFunc_GetActorForwardVector_ReturnValue) == 0x000024, "Member 'GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000030, "Member 'GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing, CallFunc_Add_VectorVector_ReturnValue) == 0x00003C, "Member 'GAB_Melee_Generic_EventGraph_C_GetLocationAtDistanceFromActorFacing::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");

// Function GAB_Melee_Generic_EventGraph.GAB_Melee_Generic_EventGraph_C.Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing
// 0x0060 (0x0060 - 0x0000)
struct GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing final
{
public:
	class AActor*                                 Actor_A;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Actor_B;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Half_Angle_Of_Actor_A_Facing;                      // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsWithinHalfAngle;                                 // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_DegCos_ReturnValue;                       // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0028(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue1;         // 0x0034(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0040(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing) == 0x000008, "Wrong alignment on GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing");
static_assert(sizeof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing) == 0x000060, "Wrong size on GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, Actor_A) == 0x000000, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::Actor_A' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, Actor_B) == 0x000008, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::Actor_B' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, Half_Angle_Of_Actor_A_Facing) == 0x000010, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::Half_Angle_Of_Actor_A_Facing' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, IsWithinHalfAngle) == 0x000014, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::IsWithinHalfAngle' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_GetActorForwardVector_ReturnValue) == 0x000018, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_DegCos_ReturnValue) == 0x000024, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_DegCos_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000028, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_K2_GetActorLocation_ReturnValue1) == 0x000034, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_K2_GetActorLocation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000040, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_Normal_ReturnValue) == 0x00004C, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_Dot_VectorVector_ReturnValue) == 0x000058, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x00005C, "Member 'GAB_Melee_Generic_EventGraph_C_Get_Is_Actor_B_Within_HalfAngle_Of_Actor_A_Facing::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");

}

