#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tiered_BluGlo_Parent

#include "Basic.hpp"


namespace SDK::Params
{

// Function Tiered_BluGlo_Parent.Tiered_BluGlo_Parent_C.ExecuteUbergraph_Tiered_BluGlo_Parent
// 0x0008 (0x0008 - 0x0000)
struct Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent) == 0x000004, "Wrong alignment on Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent");
static_assert(sizeof(Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent) == 0x000008, "Wrong size on Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent");
static_assert(offsetof(Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent, EntryPoint) == 0x000000, "Member 'Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent::EntryPoint' has a wrong offset!");
static_assert(offsetof(Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'Tiered_BluGlo_Parent_C_ExecuteUbergraph_Tiered_BluGlo_Parent::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

